# Generated by Django 3.1.4 on 2020-12-08 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3, verbose_name='Número de acta')),
                ('type', models.CharField(choices=[('SO', 'Sesión Ordinaria'), ('SE', 'Sesión Extraordinaria')], default='SO', max_length=20, verbose_name='Tipo de sesión')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('En redacción', 'En redacción'), ('En revisión', 'En revisión'), ('Aprobada', 'Aprobada')], default='En redacción', max_length=30)),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Actas',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Evidencia')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Acuerdo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='A.IINF', max_length=10, verbose_name='Prefijo')),
                ('number', models.CharField(max_length=3, verbose_name='Número')),
                ('session', models.CharField(choices=[('SO', 'Sesión Ordinaria'), ('SE', 'Sesión Extraordinaria')], default='SO', max_length=20, verbose_name='Tipo de sesión')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('name', models.CharField(max_length=255, verbose_name='Acuerdo')),
                ('description', models.TextField(verbose_name='Descripción del acuerdo')),
                ('status', models.CharField(choices=[('En proceso', 'En proceso'), ('Concluido', 'Concluido'), ('Iniciado', 'Iniciado')], default='Iniciado', max_length=30, verbose_name='Estado')),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.evidencia')),
            ],
            options={
                'verbose_name': 'Acuerdo',
                'verbose_name_plural': 'Acuerdos',
                'ordering': ['id'],
            },
        ),
    ]
