# Generated by Django 3.1.4 on 2020-12-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='acuerdos',
            field=models.ManyToManyField(to='academia.Acuerdo'),
        ),
    ]
