# Generated by Django 3.1.4 on 2020-12-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_acta_acuerdos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Asistente')),
                ('appointment', models.CharField(choices=[('Medio tiempo', 'Medio tiempo'), ('Tres cuartos de tiempo', 'Tres cuartos de tiempo'), ('Tiempo completo', 'Tiempo completo')], default='Medio tiempo', max_length=50, verbose_name='Nombramiento')),
                ('academicbody', models.CharField(choices=[('Innovación disruptiva', 'Innovación disruptiva'), ('Mejora contínua', 'Mejora contínua')], default='', max_length=100, verbose_name='Cuerpo académico')),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
                'ordering': ['appointment'],
            },
        ),
    ]
