# Generated by Django 3.1.4 on 2020-12-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_asistentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='asistentes',
            field=models.ManyToManyField(to='academia.Asistentes'),
        ),
    ]
